#
# Copyright (c) Siemens AG, 2020-2022
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This file is subject to the terms and conditions of the MIT License.  See
# COPYING.MIT file in the top-level directory.
#

image: ghcr.io/siemens/kas/kas-isar:3.1

variables:
  GIT_STRATEGY: clone

all:
  stage: build
  script:
    - export http_proxy=$HTTP_PROXY
    - export https_proxy=$HTTPS_PROXY
    - export ftp_proxy=$FTP_PROXY
    - export no_proxy=$NO_PROXY

    - kas build kas-iot2050-example.yml
    - kas build kas-iot2050-example.yml:kas/opt/preempt-rt.yml
    - kas build kas-iot2050-swupdate.yml
    - sudo rm -rf build/tmp
    - kas build kas-iot2050-boot-pg1.yml
    - sudo rm -rf build/tmp
    - kas build kas-iot2050-boot-pg2.yml
