name: 'Free Disk Space'
description: 'Remove content of the provided image to free disk space for the build'
runs:
  using: "composite"
  steps:
      - name:  Free disk space
        run: |
          sudo apt-get purge 'dotnet*' google-chrome-stable 'temurin*' google-cloud-sdk azure-cli 'mongodb*' powershell firefox chromium 'llvm*' 'libllvm*' 'mysql*' libgl1-mesa-dri apache2 'mono*' 'swift*' microsoft-edge-stable default-jre-headless 'aspnetcore*' 
          sudo rm -rf /usr/local/* /opt/hostedtoolcache /opt/pipx* /opt/az
        shell: bash
      - name: Show disk space usage
        run:  df -h
        shell: bash
