name: CI

on:
  workflow_dispatch:
    inputs:
      build_debian_example_image:
        description: 'Build Debian example image'
        required: false
        default: true
        type: boolean
      build_debian_example_qemu_image:
        description: 'Build Debian example QEMU image'
        required: false
        default: true
        type: boolean
      build_debian_swupdate_image:
        description: 'Build Debian secure boot SWUpdate image'
        required: false
        default: true
        type: boolean
      build_debian_swupdate_qemu_image:
        description: 'Build Debian SWUpdate QEMU image'
        required: false
        default: true
        type: boolean
      build_bootloaders:
        description: 'Build bootloaders'
        required: false
        default: true
        type: boolean
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '**.md'
      - '.github/workflows/link-check.yml'
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
      - '.github/workflows/link-check.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  debian-example-image:
    name: Debian example image
    if: github.event_name != 'workflow_dispatch' || inputs.build_debian_example_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Mock EIO binary stubs
        run: |
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/iot2050-eiofsd
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/map3-fw.bin
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/firmware-version
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: iot2050-example-image
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic
            build/tmp/deploy/images/iot2050/iot2050-image-example-iot2050-debian-iot2050.wic.bmap

  debian-example-qemu-image:
    name: Debian example QEMU image
    if: github.event_name != 'workflow_dispatch' || inputs.build_debian_example_qemu_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Mock EIO binary stubs
        run: |
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/iot2050-eiofsd
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/map3-fw.bin
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/firmware-version
      - name: Build image
        run: ./kas-container build kas-iot2050-example.yml:kas-iot2050-qemu.yml

  debian-swupdate-image:
    name: Debian secure boot SWUpdate image
    if: github.event_name != 'workflow_dispatch' || inputs.build_debian_swupdate_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Mock EIO binary stubs
        run: |
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/iot2050-eiofsd
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/map3-fw.bin
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/firmware-version
      - name: Build image
        run: ./kas-container build kas-iot2050-swupdate.yml:kas/opt/secure-boot.yml:kas/opt/preempt-rt.yml
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: iot2050-secureboot-swu-image
          path: |
            build/tmp/deploy/images/iot2050/iot2050-image-swu-example-iot2050-debian-iot2050.wic
            build/tmp/deploy/images/iot2050/iot2050-image-swu-example-iot2050-debian-iot2050.wic.bmap

  debian-swupdate-qemu-image:
    name: Debian SWUpdate QEMU image
    if: github.event_name != 'workflow_dispatch' || inputs.build_debian_swupdate_qemu_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Mock EIO binary stubs
        run: |
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/iot2050-eiofsd
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/map3-fw.bin
          touch ./meta-sm/recipes-app/iot2050-eiofsd/files/bin/firmware-version
      - name: Build image
        run: ./kas-container build kas-iot2050-swupdate.yml:kas-iot2050-qemu.yml

  bootloaders:
    name: Bootloaders
    if: github.event_name != 'workflow_dispatch' || inputs.build_bootloaders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Build bootloader image
        run: ./kas-container build kas-iot2050-boot.yml
      - name: Archive bootloaders
        uses: actions/upload-artifact@v4
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
